### ISSUE TITLE
Bluetooth Monterey

### ISSUE THREAD

**Issue by zajavzek** [chilledHamza/Hackintosh_Legion_Y530#4]
Bluetooth totally not working on monterey. Cannot turn on. Wifi works perfectky (2.4/5hgz) DW1820a

**Comment by chilledHamza** [comment]
As mentioned in Issues section, Bluetooth have issues on Monterey. Bluetooth works at cold boot, stops works after sleep and if you manually turn it off, it will refuse to turn on again. 

To fix it after sleep or turn off -> "sudo killall bluetoothd"

If i misunderstood your issue and Bluetooth doesn't work at all even after cold boot, make sure you are using latest EFI and attach problem reporting files.

**Comment by chilledHamza** [comment]
Just Tested new build. Bluetooth is working after sleep, and Turn On/Off button is also fixed.

Pushed changes to main branch, can you confirm that it's fixed for you as well?

**Comment by chilledHamza** [comment]
Fixed in 837735c87eaeb489297525621032e2d562215775
