### ISSUE TITLE
Stuck on apple logo

### ISSUE THREAD

**Issue by Plagg06** [chilledHamza/Hackintosh_Legion_Y530#5]
Hello, I did everything listed up until copy the EFI folder to the EFI partition in the usb. I tried to boot the installer and then I am greeted with an apple logo with no bar under it is this normal?

**Comment by chilledHamza** [comment]
> I am greeted with an apple logo with no bar under it is this normal?

Not normal, Try to boot in `verbose mode` with either `Command + V  (WIN + V)` or add ` -v ` to `boot-args` variable in NVRAM section of config.plist

Normally this behavior is possible if you don't disable MSR_E2 (CFG-Lock) in BIOS, but verbose mode should be enough to figure out actual issue here.

**Comment by Plagg06** [comment]
Hello @chilledHamza , thank you so much for taking the time to look into this for me, yes I noticed that I didn’t do any of the advanced BIOS settings did them all and it loaded normally. However there are some other issues I am facing: 
ps Sorry I have so many questions I’m very new to this
1. I cannot install macOS Big Sur onto my 256GB SSD, the laptop just crashes and stays frozen till reboot at 16 minutes remaining, so I installed to my 1TB HDD. I would like to know how to make it work on SSD tho.
2. I ran the Audiofix.sh included in the EFI/OC folder, and when I plug in headphones I hear a weird crack if there is no sound after some time, as if the headphones are waking up or something, the sound is high quality and works tho I’m not sure why there are cracks after inactive time.
3. I have the Realtek WiFi and bluetooth, I need to buy a WiFi and bluetooth adapter if I want them to work correct?
4. Just to make sure I did everything right. I was supposed to boot off my macOS Big Sur installer that had the EFI folder in the EFI partition I was supposed to mount with OC configurator and then I was supposed to boot it from my pc then install macOS and then finally copy the EFI folder to the EFI partition when macOS is installed so I don’t need the USB to boot macOS. Correct?
5. I copied SMCLightSensor.kext to the EFI kexts folder and still don’t have auto brightness, how can I make it work?
6. I can’t get Netflix to work on Safari. Is there any possible way? Note I added the shikigva=80 to my config via OC configurator , no difference 

thank you so much again for helping me

**Comment by chilledHamza** [comment]
> 1. I cannot install macOS Big Sur onto my 256GB SSD, the laptop just crashes and stays frozen till reboot at 16 minutes remaining, so I installed to my 1TB HDD. I would like to know how to make it work on SSD tho.

I guess your NVMe is Samsung PM981 or PM991, if that is true then you need to swap NVMe with compatible one (PM981/PM991 are not supported on Mac)

> 2. I ran the Audiofix.sh included in the EFI/OC folder, and when I plug in headphones I hear a weird crack if there is no sound after some time, as if the headphones are waking up or something, the sound is high quality and works tho I’m not sure why there are cracks after inactive time.

That is pretty much normal, most audio controllers give that crack/pop sounds on controller wake/sleep (depends on audio inactivity). Most XPS laptops have it on windows as well. As a workaround you can use USB/USB-C Headphones/Audio Adapter.

> 3. I have the Realtek WiFi and bluetooth, I need to buy a WiFi and bluetooth adapter if I want them to work correct?

That is correct, need to swap with compatible Broadcom chipset or original Apple Wireless module (with M2 adapter) for best result. For cheaper solution you can try Intel Wireless, but drivers are still in development so bugs are expected. plus no AirDrop support (as of right now).

> 4. Just to make sure I did everything right. I was supposed to boot off my macOS Big Sur installer that had the EFI folder in the EFI partition I was supposed to mount with OC configurator and then I was supposed to boot it from my pc then install macOS and then finally copy the EFI folder to the EFI partition when macOS is installed so I don’t need the USB to boot macOS. Correct?

Yep, all that is fine. personally I'll prefer not to use OC configurator for editing config.plist, mounting EFI Partition is fine. but there are other ways to Mount EFI Partition as well, I normally use `diskutil mount` command from terminal. for editing config consider using ProperTree, PlistEdit Pro etc. (avoid Xcode as well).

> 5. I copied SMCLightSensor.kext to the EFI kexts folder and still don’t have auto brightness, how can I make it work?

I'm not sure about this one, My Laptop does not have an Ambient Light sensor, but if you got one it should technically work with SMCLightSensor.

> 6. I can’t get Netflix to work on Safari. Is there any possible way? Note I added the shikigva=80 to my config via OC configurator , no difference

To my knowledge DRM is broken on Hackintosh  Laptop/Dekstop (iGPU only), also from what I remember shikigva stuff works with macOS 10.15 Catalina (not supported on Big Sur). 
DRM is supported on Desktops with AMD/Nvidia GPUs.

For Netflix: may be, try different browser. Chrome, Firefox etc.

**Comment by Plagg06** [comment]
Thank you so much for the reply. I have a few more questions, if you don't mind?

> That is correct, need to swap with compatible Broadcom chipset or original Apple Wireless module (with M2 adapter) for best result. For cheaper solution you can try Intel Wireless, but drivers are still in development so bugs are expected. plus no AirDrop support (as of right now).

No I mean, Can I buy a Wifi and Bluetooth USB adapter (tp-link or something like that from a local store) and attach it to my laptop while using Hackintosh and have full functionality (including Airdrop and continuity)

> I guess your NVMe is Samsung PM981 or PM991, if that is true then you need to swap NVMe with compatible one (PM981/PM991 are not supported on Mac)

I don't think that's the one I have in disk utility it says its called "SAMSUNG MZVLB256HAHQ-000L2 Media", also I have windows 11 already on that SSD, so I just partitioned it and added a APFS container partition and tried to install Hackintosh on it. I now have created an image of my windows partition using disk utility and I'm trying to restore it to a partition on my HDD, but I get this each time:
`Restoring “W” from “Windows 11.dmg”

Validating target...
Validating source...
Could not find any mountable partitions in image "/Users/mahmoudgomaa/Documents/Windows 11.dmg"
Could not validate source - Operation not supported
The operation couldn’t be completed. (OSStatus error 45.)

Operation failed…
`
furthermore if I try to directly restore the image from the existing partition it says this : `Restoring “W” from “”

Validating target...
Validating source...
Repartitioning target device...
Could not change the partition type for /dev/disk2s4 - error -5344
The operation couldn’t be completed. (OSStatus error -5344.)

Operation failed…
`
I don't understand the problem, Windows is installed to a GPT partition.

**Comment by chilledHamza** [comment]
> > That is correct, need to swap with compatible Broadcom chipset or original Apple Wireless module (with M2 adapter) for best result. For cheaper solution you can try Intel Wireless, but drivers are still in development so bugs are expected. plus no AirDrop support (as of right now).
> 
> No I mean, Can I buy a Wifi and Bluetooth USB adapter (tp-link or something like that from a local store) and attach it to my laptop while using Hackintosh
> 

Technically possible, but not a reliable solution. Y530 have three USB-A ports, if you use one for Wi-Fi and one for Bluetooth then you are only left with single USB-A port. Bluetooth is simple and easy, some devices don't event need Firmware Injection. You can possibly also get Realtek Bluetooth to work with right firmware (not sure if there is any Kext for Realtek Bluetooth). Wi-Fi over USB is little complicated, with Big Sur you will have to disable SecureBootModel along with "System Integrity Protection" and even then you might have to install drivers in /L/E for best results (which will require you to remount system drive with read/write permissions)

Bluetooth : TP-Link UB400 is supported out-of-box (will need BlueToolFix on Monterey), there are some other that work on mac without major issue.
Wi-Fi : I have used TP-Link WN725N with macOS 10.15 Catalina (on another laptop), [List of Supported Adapters](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter)

> have full functionality (including Airdrop and continuity)

No, Full functionality including AirDrop/Continuity requires Broadcom Wireless Module. Continuity alone is somewhat supported with Intel Wireless, but no AirDrop support as of right now.

> > I guess your NVMe is Samsung PM981 or PM991, if that is true then you need to swap NVMe with compatible one (PM981/PM991 are not supported on Mac)
> 
> I don't think that's the one I have in disk utility it says its called "SAMSUNG MZVLB256HAHQ-000L2 Media"

Possibly PM981 (Google : "MZVLB256HAHQ"), so you need to change NVMe to use on macOS.

> I now have created an image of my windows partition using disk utility and I'm trying to restore it to a partition on my HDD

Never tried to restore NTFS volume from Disk Utility, Mac/Disk Utility have limited read support for NTFS volumes that might be the reason you cannot complete restore process. There might be some other way to restore using Linux (GParted may be).
